import { PageLayout } from '@/components/page-layout'
import { CodeBlock } from '@/components/code-block'

export default function ResponsivePage() {
  return (
    <PageLayout
      title="Responsive"
      description="Hollows UI empty states adapt to any viewport size automatically."
      breadcrumbs={[{ name: 'Advanced' }, { name: 'Responsive' }]}
      prev={{ name: 'Copy & Language', href: '/copy' }}
      next={{ name: 'Performance', href: '/performance' }}
      tableOfContents={[
        { id: 'overview', title: 'Overview', level: 2 },
        { id: 'breakpoints', title: 'Breakpoint Configuration', level: 2 },
        { id: 'illustration-scaling', title: 'Illustration Scaling', level: 2 },
        { id: 'layout-adaptation', title: 'Layout Adaptation', level: 2 },
        { id: 'container-queries', title: 'Container Queries', level: 2 },
        { id: 'hiding-elements', title: 'Hiding Elements at Breakpoints', level: 2 },
      ]}
    >
      {/* Overview */}
      <section id="overview">
        <h2 className="font-serif text-2xl text-text-heading mb-4">Overview</h2>
        <p className="text-text-muted mb-4 leading-relaxed">
          Empty states generated by Hollows UI are responsive by default. Illustrations
          scale down, text reflows, and CTA buttons stack vertically on small screens.
          No extra configuration is needed for basic responsive behavior.
        </p>
        <div className="rounded-xl border border-border bg-surface/30 p-6 mb-6">
          <div className="flex items-end gap-4 justify-center">
            {/* Mobile */}
            <div className="text-center">
              <div className="w-16 h-28 rounded border border-border bg-[#f5f5f4] flex flex-col items-center justify-center p-2 gap-1">
                <div className="w-6 h-6 rounded bg-accent/20" />
                <div className="w-10 h-1 rounded bg-text-dim/30" />
                <div className="w-8 h-1 rounded bg-text-dim/20" />
                <div className="w-10 h-2 rounded bg-accent/30 mt-1" />
              </div>
              <p className="text-[10px] text-text-dim mt-1">Mobile</p>
            </div>
            {/* Tablet */}
            <div className="text-center">
              <div className="w-28 h-24 rounded border border-border bg-[#f5f5f4] flex flex-col items-center justify-center p-3 gap-1.5">
                <div className="w-10 h-10 rounded bg-accent/20" />
                <div className="w-16 h-1 rounded bg-text-dim/30" />
                <div className="w-12 h-1 rounded bg-text-dim/20" />
                <div className="w-14 h-2.5 rounded bg-accent/30 mt-1" />
              </div>
              <p className="text-[10px] text-text-dim mt-1">Tablet</p>
            </div>
            {/* Desktop */}
            <div className="text-center">
              <div className="w-44 h-24 rounded border border-border bg-[#f5f5f4] flex items-center justify-center p-4 gap-4">
                <div className="w-14 h-14 rounded bg-accent/20 shrink-0" />
                <div className="flex flex-col gap-1">
                  <div className="w-20 h-1.5 rounded bg-text-dim/30" />
                  <div className="w-16 h-1 rounded bg-text-dim/20" />
                  <div className="w-14 h-2.5 rounded bg-accent/30 mt-1" />
                </div>
              </div>
              <p className="text-[10px] text-text-dim mt-1">Desktop</p>
            </div>
          </div>
        </div>
      </section>

      {/* Breakpoints */}
      <section id="breakpoints" className="mt-12">
        <h2 className="font-serif text-2xl text-text-heading mb-4">Breakpoint Configuration</h2>
        <p className="text-text-muted mb-4 leading-relaxed">
          Customize the breakpoints used for responsive behavior. By default, Hollows
          uses the same breakpoint scale as Tailwind CSS.
        </p>

        <div className="rounded-xl border border-border bg-surface/30 p-4 mb-6">
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border">
                  <th className="text-left py-2 pr-4 text-text-dim font-medium">Name</th>
                  <th className="text-left py-2 pr-4 text-text-dim font-medium">Default</th>
                  <th className="text-left py-2 text-text-dim font-medium">Behavior</th>
                </tr>
              </thead>
              <tbody className="text-text-muted">
                <tr className="border-b border-border/50">
                  <td className="py-2 pr-4 font-mono text-xs text-accent">sm</td>
                  <td className="py-2 pr-4 font-mono text-xs">640px</td>
                  <td className="py-2 text-xs">Stacked layout, small illustrations</td>
                </tr>
                <tr className="border-b border-border/50">
                  <td className="py-2 pr-4 font-mono text-xs text-accent">md</td>
                  <td className="py-2 pr-4 font-mono text-xs">768px</td>
                  <td className="py-2 text-xs">Centered layout, medium illustrations</td>
                </tr>
                <tr className="border-b border-border/50">
                  <td className="py-2 pr-4 font-mono text-xs text-accent">lg</td>
                  <td className="py-2 pr-4 font-mono text-xs">1024px</td>
                  <td className="py-2 text-xs">Horizontal layout available, full illustrations</td>
                </tr>
                <tr>
                  <td className="py-2 pr-4 font-mono text-xs text-accent">xl</td>
                  <td className="py-2 pr-4 font-mono text-xs">1280px</td>
                  <td className="py-2 text-xs">Max-width capped, extra breathing room</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <CodeBlock
          language="ts"
          filename="hollows.config.ts"
          code={`import { defineConfig } from 'hollows-ui'

export default defineConfig({
  responsive: {
    breakpoints: {
      sm: '480px',  // custom mobile breakpoint
      md: '768px',
      lg: '1024px',
      xl: '1440px', // wider desktop
    },
  },
})`}
        />
      </section>

      {/* Illustration Scaling */}
      <section id="illustration-scaling" className="mt-12">
        <h2 className="font-serif text-2xl text-text-heading mb-4">Illustration Scaling</h2>
        <p className="text-text-muted mb-4 leading-relaxed">
          Illustration sizes adapt automatically at each breakpoint. You can customize
          the max-width at each size.
        </p>

        <CodeBlock
          language="ts"
          filename="hollows.config.ts"
          code={`import { defineConfig } from 'hollows-ui'

export default defineConfig({
  responsive: {
    illustration: {
      sm: { maxWidth: 64, hidden: false },
      md: { maxWidth: 96 },
      lg: { maxWidth: 120 },
      xl: { maxWidth: 160 },
    },
  },
})`}
        />

        <p className="text-text-muted mt-4 leading-relaxed">
          Set <code className="bg-surface border border-border px-1.5 py-0.5 rounded text-sm font-mono text-accent">hidden: true</code>{' '}
          at any breakpoint to hide the illustration entirely. This is useful on very small
          screens where space is limited.
        </p>

        <CodeBlock
          language="ts"
          code={`// Hide illustration on mobile, show from md up
responsive: {
  illustration: {
    sm: { hidden: true },
    md: { maxWidth: 96 },
    lg: { maxWidth: 120 },
  },
}`}
        />
      </section>

      {/* Layout Adaptation */}
      <section id="layout-adaptation" className="mt-12">
        <h2 className="font-serif text-2xl text-text-heading mb-4">Layout Adaptation</h2>
        <p className="text-text-muted mb-4 leading-relaxed">
          On smaller screens, empty states switch to a vertical (stacked) layout. On larger
          screens, a horizontal layout places the illustration alongside the text. Control
          this behavior with the <code className="bg-surface border border-border px-1.5 py-0.5 rounded text-sm font-mono text-accent">layout</code> option.
        </p>

        <CodeBlock
          language="ts"
          filename="hollows.config.ts"
          code={`import { defineConfig } from 'hollows-ui'

export default defineConfig({
  responsive: {
    layout: {
      // Below md: always stack vertically
      sm: 'vertical',
      // md and up: use horizontal layout if illustration exists
      md: 'horizontal',
      // Or force vertical everywhere
      // sm: 'vertical', md: 'vertical', lg: 'vertical',
    },
    maxWidth: {
      sm: '100%',
      md: '480px',
      lg: '560px',
      xl: '640px',
    },
  },
})`}
        />
      </section>

      {/* Container Queries */}
      <section id="container-queries" className="mt-12">
        <h2 className="font-serif text-2xl text-text-heading mb-4">Container Queries</h2>
        <p className="text-text-muted mb-4 leading-relaxed">
          By default, Hollows uses viewport-based breakpoints. Enable container queries
          to make empty states adapt based on their parent container width instead. This
          is ideal for dashboard widgets, sidebars, and other constrained layouts.
        </p>

        <CodeBlock
          language="ts"
          filename="hollows.config.ts"
          code={`import { defineConfig } from 'hollows-ui'

export default defineConfig({
  responsive: {
    strategy: 'container', // 'viewport' (default) | 'container'
  },
})`}
        />

        <p className="text-text-muted mt-4 leading-relaxed">
          With container queries enabled, the{' '}
          <code className="bg-surface border border-border px-1.5 py-0.5 rounded text-sm font-mono text-accent">.hollows-root</code>{' '}
          element gets{' '}
          <code className="bg-surface border border-border px-1.5 py-0.5 rounded text-sm font-mono text-accent">container-type: inline-size</code>{' '}
          and all responsive rules use{' '}
          <code className="bg-surface border border-border px-1.5 py-0.5 rounded text-sm font-mono text-accent">@container</code>{' '}
          instead of{' '}
          <code className="bg-surface border border-border px-1.5 py-0.5 rounded text-sm font-mono text-accent">@media</code>.
        </p>
      </section>

      {/* Hiding Elements */}
      <section id="hiding-elements" className="mt-12">
        <h2 className="font-serif text-2xl text-text-heading mb-4">Hiding Elements at Breakpoints</h2>
        <p className="text-text-muted mb-4 leading-relaxed">
          Control which parts of the empty state are visible at each breakpoint.
        </p>

        <CodeBlock
          language="ts"
          filename="hollows.config.ts"
          code={`import { defineConfig } from 'hollows-ui'

export default defineConfig({
  responsive: {
    visibility: {
      illustration: { sm: false, md: true },
      body: { sm: false, md: true },
      cta: { sm: true, md: true },
      heading: { sm: true, md: true },
    },
  },
})`}
        />

        <p className="text-text-muted mt-4 leading-relaxed">
          In this example, on small screens only the heading and CTA are shown.
          The illustration and body text appear from the{' '}
          <code className="bg-surface border border-border px-1.5 py-0.5 rounded text-sm font-mono text-accent">md</code>{' '}
          breakpoint and up.
        </p>
      </section>
    </PageLayout>
  )
}
