import * as fs from 'fs'
import * as path from 'path'
import type { HollowDescriptor } from '../core/types'

export function generateRegistry(outDir: string): string {
  const files = fs.readdirSync(outDir).filter(f => f.endsWith('.hollows.json'))

  const imports: string[] = []
  const entries: string[] = []

  for (const file of files) {
    const name = file.replace('.hollows.json', '')
    const varName = name.replace(/[^a-zA-Z0-9]/g, '_')
    imports.push(`import ${varName} from './${file}'`)
    entries.push(`  '${name}': ${varName},`)
  }

  const registryContent = `// Auto-generated by hollows-ui — do not edit manually
${imports.join('\n')}

const registry = {
${entries.join('\n')}
}

if (typeof globalThis !== 'undefined') {
  ;(globalThis as any).__HOLLOWS_REGISTRY__ = registry
}

export default registry
`

  const registryPath = path.join(outDir, 'registry.ts')
  fs.writeFileSync(registryPath, registryContent, 'utf-8')
  return registryPath
}

export function generateRegistryJS(outDir: string): string {
  const files = fs.readdirSync(outDir).filter(f => f.endsWith('.hollows.json'))

  const entries: string[] = []

  for (const file of files) {
    const name = file.replace('.hollows.json', '')
    const content = fs.readFileSync(path.join(outDir, file), 'utf-8')
    entries.push(`  '${name}': ${content},`)
  }

  const registryContent = `// Auto-generated by hollows-ui — do not edit manually
const registry = {
${entries.join('\n')}
}

if (typeof globalThis !== 'undefined') {
  globalThis.__HOLLOWS_REGISTRY__ = registry
}

module.exports = registry
`

  const registryPath = path.join(outDir, 'registry.js')
  fs.writeFileSync(registryPath, registryContent, 'utf-8')
  return registryPath
}

// Runtime registry access
const _runtimeRegistry = new Map<string, HollowDescriptor>()

export function registerHollow(name: string, descriptor: HollowDescriptor): void {
  _runtimeRegistry.set(name, descriptor)
}

export function getHollow(name: string): HollowDescriptor | undefined {
  // Check runtime registry first
  if (_runtimeRegistry.has(name)) {
    return _runtimeRegistry.get(name)
  }

  // Check global registry (from generated registry file)
  if (typeof globalThis !== 'undefined' && (globalThis as any).__HOLLOWS_REGISTRY__) {
    return (globalThis as any).__HOLLOWS_REGISTRY__[name]
  }

  return undefined
}

export function getAllHollows(): Map<string, HollowDescriptor> {
  const all = new Map<string, HollowDescriptor>(_runtimeRegistry)

  if (typeof globalThis !== 'undefined' && (globalThis as any).__HOLLOWS_REGISTRY__) {
    const global = (globalThis as any).__HOLLOWS_REGISTRY__
    for (const [name, descriptor] of Object.entries(global)) {
      if (!all.has(name)) {
        all.set(name, descriptor as HollowDescriptor)
      }
    }
  }

  return all
}
